### ISSUE TITLE
"RangeError (index): Invalid value: Not in inclusive range 0..6: 7"

### ISSUE THREAD

**Issue by Saransh-cpp** [yashlamba/simulate#153]
Shows the same error on every tab, tried to fix it but not working. I guess something is wrong with the favourites section.

**Comment by sakshamarora1** [comment]
@Saransh-cpp The app seems to be working fine for me. We had this error a long time ago and was fixed. Can you point me to the branch you are building the app from?

Try re-forking the project and running the flutter run command from the master/main branch.

**Comment by Saransh-cpp** [comment]
Re-forked the repo, cloned it again after deleting the previous files and I am on the master branch but still getting the same issue.

**Comment by yashlamba** [comment]
@Saransh-cpp can you run `git remote -v` in the project directory you are running and share the output?

**Comment by Saransh-cpp** [comment]
`origin  https://github.com/Saransh-cpp/simulate-1.git (fetch)`
`origin  https://github.com/Saransh-cpp/simulate-1.git (push)`

@yashlamba this is the output I am getting, I also compared the code which is in my system with the actual repo using an online code comparer website, they were exactly same, and android studio is showing that I am on the master branch. I don't know where I am going wrong.

**Comment by yashlamba** [comment]
Are you using an emulator or a device?

Did you uninstall all previous versions of simulate before setup?

Can you post a screenshot and the terminal log so that we can investigate? 

I am unable to replicate this issue on my device. We had some similar error before with favorites but that was fixed too.

**Comment by Saransh-cpp** [comment]
I opened the app in another emulator and it works fine now, the problem most probably was with the older version of app installed in my emulator. So sorry for the inconvenience caused. I am closing the issue now, thanks for responding and helping me out.
